name: public-build

on:
  repository_dispatch:
    types: [build-from-private]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4

      - name: Show trigger info
        run: |
          echo "Triggered from private repo"
          echo "SHA: ${{ github.event.client_payload.sha }}"
